controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - arm0_shoulder_yaw
      - arm0_shoulder_pitch
      - arm0_elbow_pitch
      - arm0_elbow_roll
      - arm0_wrist_pitch
      - arm0_wrist_roll
  - name: fake_finger_controller
    type: $(arg fake_execution_type)
    joints:
      - arm0_fingers
initial:  # Define initial robot poses per group
  - group: arm
    pose: Ready
  - group: finger
    pose: Gripper_open