sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  # TODO change this to be the map that is continually built (may need to publish that)
    point_cloud_topic: /core_reader/collision_scan
    max_range: 30.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    max_update_rate: 1.0
    filtered_cloud_topic: filtered_cloud
    ns: kinect
