game_theoretic_painting:
  paths:
    pkg_path:                    /home/steven/game_theoretic_painting/src/
  board:
    movement:
      discretization:           3.0
    repair:
      discretization:           1.0
  party:
    n_drones:                   1
    n_quadrupeds:               1
    n_gantries:                 1
    starting_location:          12 # ? any negative number (ie. -1) will make starting locations be randomly assigned
  mcts:
    search_duration_ms:         3000 #1000 # ms
    num_candidates:             50 #20
    search_depth:               20 #5 # num party cycles to simulate ahead (p_start will play x times)
    uct_c:                      10 #1.4142136

